name: VotePlus
main: nissining.voteplus.VotePlus
version: "1"
author: Nissining
api: ["1.0.0"]
commands:
  vote:
    description: VotePlus By Nissining
  ban:
    description: VotePlus Ban
  addmoney:
    description: VotePlus MoneyAPI
  reducemoney:
    description: VotePlus MoneyAPI
  getmoney:
    description: VotePlus MoneyAPI